language: python
python:
  - 3.6
install:
  - pip install "cython>=0.29"
  - pip install -e ".[tests, docs]"
script:
  - pytest -vs --cov=imagededup --cov-report xml --show-capture=no tests
  - cd mkdocs && sh build_docs.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local-dir: docs/
  on:
    branch: master
  target_branch: gh-pages
env:
  global:
    secure: B4R9l1PzY00r/ITZfuIPunpbpMJuSrtegEyZCgy8JE/ei2sWZ0+FJ1SVausYY/g0aDumwMGITSQo6L0RafTbIG8LZ/l6KO9GuGmPsn8vYCwGd+4/eyt6nNocyGPv/4Vmm8jrgPtjUCCSGBD6mfU4nPn6bfN8Xhwl5i5ZodfXg6TfLNpYNkyauHm4L63UT6usfQ1JSE7pHb3gM88acYpTowrBm2WomgPPbKsd2isPtHbiIbOemXVpUjqygTXn7Gf8Dkq0Irasm93M3n+svAuGrhQRqfAupVlv5u+0jwQXAWhxoKAXVS/wH1n+ubN79G849VX/6B84bPGbTQS4QE9LVU+UcZ2PmyWeQZEJiwqr3T+f1bSPmu31ioGaAzxyBATm7odSht2iAGw/GzvZnL4maQAN/QhZQgjdpkQKuEURyGCEZ+87gVwpP+KUZPCiPzKRndeQTa9wiJVQk6tGwcfDD4umkqmO9Hj6lXV0UdP7ruIfhUF5IFmovBucsdLR6JL9+RzlHciDJ3905kWDQSekMo+q+tapme8qeIx0EJ6M0MohS8PXqjhS38DfZ/BkFZAxpm4gDGPaLE6wz0gAQ5ObjsMReM/drn0Bo5vEzjZCSd+f+GxlGS/Hbeos4+SCtKDNrA80m5tDoghzbVyDlRG6FGJk2+HK4JB52LPtWBoTHaE=
after_success:
  - codecov
